name: "Docker Image Build"

on:
  push:
    branches:
      - main

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          check-latest: true
      - name: mvn
        run: ./mvnw package
